# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"favorite_bird": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://YingyingF.github.io/birdsong_recognition/"

git_url = "https://github.com/YingyingF/birdsong_recognition/tree/master/"

def custom_doc_links(name): return None
